server:
  port: 8000
  undertow:
    url-charset: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

jasypt:
  encryptor:
    password: sUkWrdITR1jOxQHF

spring:
  aop:
    proxy-target-class: true

  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
#        session_factory:
#          statement_inspector: com.jemmy.framework.utils.jpa.JpaInterceptor
        search:
          default:
            directory_provider: filesystem
            indexBase: ../database
#    show-sql: true

  servlet:
    multipart:
      max-file-size: 2000000000
      max-request-size: 2000000000

  # 邮箱配置
  mail:
    host: smtp-mail.outlook.com
    username: xxx@xx.com # 邮箱地址
    password: xxxxxx # 邮箱密码
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            required: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:../upload/